### 보관함 생성
POST localhost:8080/api/box
Content-Type: application/json

{
  "phone" : "01012341234",
  "keyword": "아으닉네임",
  "title" : "타이틀"
}

### 보관함 조회
GET localhost:8080/api/box?phone=01012341234&keyword=아으닉네임